# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('battery', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Device'),
        ),
    ]
