# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20160712_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='deviceNb',
        ),
        migrations.AddField(
            model_name='device',
            name='deviceNb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
