# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20160712_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='light',
            field=models.IntegerField(null=True),
        ),
    ]
