# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20160713_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
    ]
