# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20160713_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Device')),
            ],
        ),
    ]
