# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_deviceentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='device',
            name='light',
        ),
        migrations.RemoveField(
            model_name='device',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AddField(
            model_name='device',
            name='deviceType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='accx',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='accy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='accz',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='battery',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='light',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceentry',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceentry',
            name='humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceentry',
            name='pressure',
            field=models.IntegerField(null=True),
        ),
    ]
