# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_device_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceentry',
            name='accx',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceentry',
            name='accy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceentry',
            name='accz',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceentry',
            name='datetime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deviceentry',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceentry',
            name='pressure',
            field=models.FloatField(null=True),
        ),
    ]
