# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20160719_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deviceName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
