# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_device_devicename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceentry',
            name='datetime',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
