# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_deviceentry_rssi'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deviceStatus',
            field=models.CharField(choices=[('D', 'Disconnected'), ('C', 'Connected')], max_length=100, null=True),
        ),
    ]
