# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_device_devicestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weatherOn', models.NullBooleanField()),
                ('accelerometerOn', models.NullBooleanField()),
                ('lightOn', models.NullBooleanField()),
                ('weatherPeriod', models.IntegerField(null=True)),
                ('accelerometerPeriod', models.IntegerField(null=True)),
                ('lightPeriod', models.IntegerField(null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Device')),
            ],
        ),
    ]
